### ISSUE TITLE
ScrollNet

### ISSUE THREAD

**Issue by gibru** [breck7/breckyunits.com#5]
The article [_ScrollNet: A successor to the Internet_](https://breckyunits.com/scrollnet.html) was originally published in 2013, leading me to the following question: how well do you think that idea has aged from today's perspective?

**Comment by breck7** [comment]
> how well do you think that idea has aged from today's perspective?

I had forgotten about that post because I originally posted it to Medium, and not my blog. I stumbled upon it in June of this year and migrated here. (https://github.com/breck7/breckyunits.com/commits/b877753d8435be485c11c83a8ed1a4bb49d6f3ef/spacenet.scroll?browsing_rename_history=true&new_path=scrollnet.scroll&original_branch=main)

Yesterday I did a find replace from "SpaceNet" => "ScrollNet".

I don't think it could have possibly aged better.

Back then it was more of a hunch that one could do such a thing. Maybe 51% confident. Now I'm 99.9% confident. Feels like it may happen.

That being said, back then that was my biggest idea. But now it's a relatively small one.
